# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11iot_service.proto\x12\x0biot_service\"K\n\x0bUserRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x03 \x01(\r\x12\x0b\n\x03key\x18\x04 \x01(\r\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\nLoginReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x02 \x01(\r\x12\x0b\n\x03key\x18\x03 \x01(\r\"!\n\x12AccelerationRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\"7\n\x10AccelerationReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bacceleration\x18\x02 \x01(\t\"9\n\nstate\x18\x01 \x01(\r\x12\x0f\n\x07(\t\x12\x0b\n\x03key\x18\x03 \x01(\r\"\x82\x01\n\x08status\x18\x01 \x01(\t\x12\x35\n\x08\x03(\x0b\x32key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\" \n\x11LightLevelRequest\x12\x0b\n\x03key\x18\x01 \x01(\r\"5\n\x0fLightLevelReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nlightLevel\x18\x02 \x01(\t2\xf6\x02\n\nIoTService\x12R\n\x0eSayAcceleration\x12\x1f.iot_service.AccelerationRequest\x1a\x1d.iot_service.AccelerationReply\"\x00\x12\x42\n\nCreateUser\x12\x18.iot_service.UserRequest\x1a\x18.iot_service.StatusReply\"\x00\x12\x41\n\tUserLogin\x12\x19.iot_service.LoginRequest\x1a\x17.iot_service.LoginReply\"\x00\x12<\n\x08\x42O\n\rSayLightLevel\x12\x1e.iot_service.LightLevelRequest\x1a\x1c.iot_service.LightLevelReply\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _USERREQUEST._serialized_start=34
  _USERREQUEST._serialized_end=109
  _STATUSREPLY._serialized_start=111
  _STATUSREPLY._serialized_end=140
  _LOGINREQUEST._serialized_start=142
  _LOGINREQUEST._serialized_end=189
  _LOGINREPLY._serialized_start=191
  _LOGINREPLY._serialized_end=248
  _ACCELERATIONREQUEST._serialized_start=250
  _ACCELERATIONREQUEST._serialized_end=283
  _ACCELERATIONREPLY._serialized_start=285
  _ACCELERATIONREPLY._serialized_end=340
  _LIGHTLEVELREQUEST._serialized_start=534
  _LIGHTLEVELREQUEST._serialized_end=566
  _LIGHTLEVELREPLY._serialized_start=568
  _LIGHTLEVELREPLY._serialized_end=621
  _IOTSERVICE._serialized_start=624
  _IOTSERVICE._serialized_end=998
# @@protoc_insertion_point(module_scope)
